# -*- coding: utf-8 -*-
"""
/***************************************************************************
 IndiceNDWI
                                 A QGIS plugin
 Este complemento calcula el índice NDWI con las imágenes del Landsat 8.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-11-22
        copyright            : (C) 2022 by Francisca Ruiz-Tagle Santander y Keyla Alencar da Silva - UTEM/UNR
        email                : fa.ruiztaglest@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load IndiceNDWI class from file IndiceNDWI.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .indice_ndwi import IndiceNDWI
    return IndiceNDWI(iface)
