# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\indice_ndwi_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_IndiceNDWIDialogBase(object):
    def setupUi(self, IndiceNDWIDialogBase):
        IndiceNDWIDialogBase.setObjectName("IndiceNDWIDialogBase")
        IndiceNDWIDialogBase.resize(820, 268)
        self.gridLayout_2 = QtWidgets.QGridLayout(IndiceNDWIDialogBase)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_38 = QtWidgets.QLabel(IndiceNDWIDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_38.sizePolicy().hasHeightForWidth())
        self.label_38.setSizePolicy(sizePolicy)
        self.label_38.setMouseTracking(False)
        self.label_38.setStyleSheet("background-color : #848484; color : white")
        self.label_38.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_38.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_38.setObjectName("label_38")
        self.gridLayout_2.addWidget(self.label_38, 0, 0, 1, 5)
        self.msj_TIF = QtWidgets.QLabel(IndiceNDWIDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.msj_TIF.sizePolicy().hasHeightForWidth())
        self.msj_TIF.setSizePolicy(sizePolicy)
        self.msj_TIF.setMinimumSize(QtCore.QSize(229, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.msj_TIF.setFont(font)
        self.msj_TIF.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.msj_TIF.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.msj_TIF.setObjectName("msj_TIF")
        self.gridLayout_2.addWidget(self.msj_TIF, 1, 0, 1, 1)
        self.cuadroTIF = QtWidgets.QLabel(IndiceNDWIDialogBase)
        self.cuadroTIF.setEnabled(True)
        self.cuadroTIF.setFrameShape(QtWidgets.QFrame.Panel)
        self.cuadroTIF.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.cuadroTIF.setText("")
        self.cuadroTIF.setObjectName("cuadroTIF")
        self.gridLayout_2.addWidget(self.cuadroTIF, 1, 1, 1, 3)
        self.btn_abrirTIF = QtWidgets.QToolButton(IndiceNDWIDialogBase)
        self.btn_abrirTIF.setObjectName("btn_abrirTIF")
        self.gridLayout_2.addWidget(self.btn_abrirTIF, 1, 4, 1, 1)
        self.msj_MTL = QtWidgets.QLabel(IndiceNDWIDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.msj_MTL.sizePolicy().hasHeightForWidth())
        self.msj_MTL.setSizePolicy(sizePolicy)
        self.msj_MTL.setMinimumSize(QtCore.QSize(229, 0))
        self.msj_MTL.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.msj_MTL.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.msj_MTL.setObjectName("msj_MTL")
        self.gridLayout_2.addWidget(self.msj_MTL, 2, 0, 1, 1)
        self.cuadroMTL = QtWidgets.QLabel(IndiceNDWIDialogBase)
        self.cuadroMTL.setFrameShape(QtWidgets.QFrame.Panel)
        self.cuadroMTL.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.cuadroMTL.setText("")
        self.cuadroMTL.setObjectName("cuadroMTL")
        self.gridLayout_2.addWidget(self.cuadroMTL, 2, 1, 1, 3)
        self.btn_abrirMTL = QtWidgets.QToolButton(IndiceNDWIDialogBase)
        self.btn_abrirMTL.setObjectName("btn_abrirMTL")
        self.gridLayout_2.addWidget(self.btn_abrirMTL, 2, 4, 1, 1)
        self.label_76 = QtWidgets.QLabel(IndiceNDWIDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_76.sizePolicy().hasHeightForWidth())
        self.label_76.setSizePolicy(sizePolicy)
        self.label_76.setStyleSheet("background-color : #848484; color : white")
        self.label_76.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_76.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_76.setObjectName("label_76")
        self.gridLayout_2.addWidget(self.label_76, 3, 0, 1, 5)
        self.btn_correccion = QtWidgets.QCheckBox(IndiceNDWIDialogBase)
        self.btn_correccion.setChecked(False)
        self.btn_correccion.setTristate(False)
        self.btn_correccion.setObjectName("btn_correccion")
        self.gridLayout_2.addWidget(self.btn_correccion, 4, 0, 1, 2)
        self.msj_CORR = QtWidgets.QLabel(IndiceNDWIDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.msj_CORR.sizePolicy().hasHeightForWidth())
        self.msj_CORR.setSizePolicy(sizePolicy)
        self.msj_CORR.setMinimumSize(QtCore.QSize(229, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.msj_CORR.setFont(font)
        self.msj_CORR.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.msj_CORR.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.msj_CORR.setObjectName("msj_CORR")
        self.gridLayout_2.addWidget(self.msj_CORR, 5, 0, 1, 1)
        self.cuadroBandasCorregidas = QtWidgets.QLabel(IndiceNDWIDialogBase)
        self.cuadroBandasCorregidas.setEnabled(True)
        self.cuadroBandasCorregidas.setFrameShape(QtWidgets.QFrame.Panel)
        self.cuadroBandasCorregidas.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.cuadroBandasCorregidas.setText("")
        self.cuadroBandasCorregidas.setObjectName("cuadroBandasCorregidas")
        self.gridLayout_2.addWidget(self.cuadroBandasCorregidas, 5, 1, 1, 3)
        self.btn_abrirCORR = QtWidgets.QToolButton(IndiceNDWIDialogBase)
        self.btn_abrirCORR.setObjectName("btn_abrirCORR")
        self.gridLayout_2.addWidget(self.btn_abrirCORR, 5, 4, 1, 1)
        self.label_77 = QtWidgets.QLabel(IndiceNDWIDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_77.sizePolicy().hasHeightForWidth())
        self.label_77.setSizePolicy(sizePolicy)
        self.label_77.setStyleSheet("background-color : #848484; color : white")
        self.label_77.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_77.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_77.setObjectName("label_77")
        self.gridLayout_2.addWidget(self.label_77, 6, 0, 1, 5)
        self.cuadroGuardar = QtWidgets.QLabel(IndiceNDWIDialogBase)
        self.cuadroGuardar.setFrameShape(QtWidgets.QFrame.Panel)
        self.cuadroGuardar.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.cuadroGuardar.setText("")
        self.cuadroGuardar.setObjectName("cuadroGuardar")
        self.gridLayout_2.addWidget(self.cuadroGuardar, 7, 0, 1, 4)
        self.btn_guardar = QtWidgets.QToolButton(IndiceNDWIDialogBase)
        self.btn_guardar.setObjectName("btn_guardar")
        self.gridLayout_2.addWidget(self.btn_guardar, 7, 4, 1, 1)
        self.btn_ejecutar = QtWidgets.QPushButton(IndiceNDWIDialogBase)
        self.btn_ejecutar.setObjectName("btn_ejecutar")
        self.gridLayout_2.addWidget(self.btn_ejecutar, 8, 2, 1, 1)
        self.btn_cerrar = QtWidgets.QPushButton(IndiceNDWIDialogBase)
        self.btn_cerrar.setObjectName("btn_cerrar")
        self.gridLayout_2.addWidget(self.btn_cerrar, 8, 3, 1, 1)

        self.retranslateUi(IndiceNDWIDialogBase)
        QtCore.QMetaObject.connectSlotsByName(IndiceNDWIDialogBase)

    def retranslateUi(self, IndiceNDWIDialogBase):
        _translate = QtCore.QCoreApplication.translate
        IndiceNDWIDialogBase.setWindowTitle(_translate("IndiceNDWIDialogBase", "Moisture and Water Index"))
        self.label_38.setText(_translate("IndiceNDWIDialogBase", "Entrada de datos sin procesar "))
        self.msj_TIF.setText(_translate("IndiceNDWIDialogBase", "Directorio contenedor bandas Landsat 8 "))
        self.btn_abrirTIF.setText(_translate("IndiceNDWIDialogBase", "..."))
        self.msj_MTL.setToolTip(_translate("IndiceNDWIDialogBase", "<html><head/><body><p>Select MTL file (if not in Landsat directory)</p></body></html>"))
        self.msj_MTL.setText(_translate("IndiceNDWIDialogBase", "Seleccionar archivo MTL"))
        self.btn_abrirMTL.setText(_translate("IndiceNDWIDialogBase", "..."))
        self.label_76.setText(_translate("IndiceNDWIDialogBase", "Corrección atmosférica (Radiancia y reflectancia TOA)"))
        self.btn_correccion.setToolTip(_translate("IndiceNDWIDialogBase", "<html><head/><body><p>Enable/Disable calculation of temperature in Celsius from thermal band</p></body></html>"))
        self.btn_correccion.setText(_translate("IndiceNDWIDialogBase", "Corrección realizada "))
        self.msj_CORR.setText(_translate("IndiceNDWIDialogBase", "Directorio contenedor bandas corregidas "))
        self.btn_abrirCORR.setText(_translate("IndiceNDWIDialogBase", "..."))
        self.label_77.setText(_translate("IndiceNDWIDialogBase", "Cálculo NDWI (Xu, Gao y McFeeters)"))
        self.btn_guardar.setText(_translate("IndiceNDWIDialogBase", "..."))
        self.btn_ejecutar.setText(_translate("IndiceNDWIDialogBase", "Ejecutar"))
        self.btn_cerrar.setText(_translate("IndiceNDWIDialogBase", "Cerrar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    IndiceNDWIDialogBase = QtWidgets.QDialog()
    ui = Ui_IndiceNDWIDialogBase()
    ui.setupUi(IndiceNDWIDialogBase)
    IndiceNDWIDialogBase.show()
    sys.exit(app.exec_())
